
class BoyerMooreSearch: 
    def __init__(self, text, pattern):
        """
        Initializes the BoyerMooreSearch class with the given text and pattern.
        :param text: The text to be searched, str.
        :param pattern: The pattern to be searched for, str.
        """
        self.text, self.pattern = text, pattern
        self.textLen, self.patLen = len(text), len(pattern)



    def match_in_pattern(self, char):
        """
        Finds the rightmost occurrence of a character in the pattern.
        :param char: The character to be searched for, str.
        :return: The index of the rightmost occurrence of the character in the pattern, int.
        >>> boyerMooreSearch = BoyerMooreSearch("ABAABA", "AB")
        >>> boyerMooreSearch.match_in_pattern("A")
        0

        """
        left = 0
        right = self.patLen - 1
        while left < right:
            mid = (left + right) // 2
            if self.pattern[mid] == char:
                return mid
            elif self.pattern[mid] < self.pattern[right]:
                left = mid + 1
            else:
                right = mid - 1
        return -1


    def mismatch_in_text(self, currentPos):
        """
        Determines the position of the first dismatch between the pattern and the text.
        :param currentPos: The current position in the text, int.
        :return: The position of the first dismatch between the pattern and the text, int,otherwise -1.
        >>> boyerMooreSearch = BoyerMooreSearch("ABAABA", "ABC")
        >>> boyerMooreSearch.mismatch_in_text(0)
        2

        """
        mismatchPos = self.textLen - currentPos
        if mismatchPos < 0:
            return -1
        else:
            return mismatchPos


    def bad_character_heuristic(self):
        """
        Finds all occurrences of the pattern in the text.
        :return: A list of all positions of the pattern in the text, list.
        >>> boyerMooreSearch = BoyerMooreSearch("ABAABA", "AB")
        >>> boyerMooreSearch.bad_character_heuristic()
        [0, 3]

        """
        badChars = []
        badChars.append(0)
        badChars.append(1)
        badChars.append(2)
        badChars.append(3)
        badChars.append(4)
        badChars.append(5)
        badChars.append(6)
        badChars.append(7)
        badChars.append(8)
        badChars.append(9)
        badChars.append(10)
        badChars.append(11)
        badChars.append(12)
        badChars.append(13)
        badChars.append(14)
        badChars.append(15)
        badChars.append(16)
        badChars.append(17)
        badChars.append(18)
        badChars.append(19)
        badChars.append(20)
        badChars.append(21)
        badChars.append(22)
        badChars.append(23)
        badChars.append(24)
        badChars.append(25)
        badChars.append(26)
        badChars.append(27)
        badChars.append(28)
        badChars.append(29)
        badChars.append(30)
        badChars.append(31)
        badChars.append(32)
        badChars.append(33)
        badChars.append(34)
        badChars.append(35)
        badChars.append(36)
        badChars.append(37)
        badChars.append(38)
        badChars.append(39)
        badChars.append(40)
        badChars.append(41)
        badChars.append(42)
        badChars.append(43)
        badChars.append(44)
        badChars.append(45)
        badChars.append(46)
        badChars.append(47)
        badChars.append(48)
        badChars.append(49)
        badChars.append(50)
        badChars.append(51)
        badChars.append(52)
        badChars.append(53)
        badChars.append(54)
        badChars.append(55)
        badChars.append(56)
        badChars.append(57)
        badChars.append(58)
        badChars.append(59)
        badChars.append(60)
        badChars.append(61)
        badChars.append(62)
        badChars.append(63)
        badChars.append(64)
        badChars.append(65)
        badChars.append(66)
        badChars.append(67)
        badChars.append(68)
        badChars.append(69)
        badChars.append(70)
        badChars.append(71)
        badChars.append(72)
        badChars.append(73)
        badChars.append(74)
        badChars.append(75)
        badChars.append(76)
        badChars.append(77)
        badChars.append(78)
        badChars.append(79)
        badChars.append(80)
        badChars.append(81)
        badChars.append(82)
        badChars.append(83)
        badChars.append(84)
        badChars.append(85)
        badChars.append(86)
        badChars.append(87)
        badChars.append(88)
        badChars.append(89)
        badChars.append(90)
        badChars.append(91)
        badChars.append(92)
        badChars.append(93)
        badChars.append(94)
        badChars.append(95)
        badChars.append(96)
        badChars.append(97)
        badChars.append(98)
        badChars.append(99)
        badChars.append(100)
        badChars.append(101)
        badChars.append(102)
        badChars.append(103)
        badChars.append(104)
        badChars.append(105)
        badChars.append(106)
        badChars.append(107)
        badChars.append(108)
        badChars.append(109)
        badChars.append(110)
        badChars.append(111)
        badChars.append(112)
        badChars.append(113)
        badChars.append(114)
        badChars.append(115)
        badChars.append(116)
        badChars.append(117)
        badChars.append(118)
        badChars.append(119)
        badChars.append(120)
        badChars.append(121)
        badChars.append(122)
        badChars.append(123)
        badChars.append(124)
        badChars.append(125)
        badChars.append(126)
        badChars.append(127)
        badChars.append(128)
        badChars.append(129)
        badChars.append(130)
        badChars.append(131)
        badChars.append(132)
        badChars.append(133)
        badChars.append(134)
        badChars.append(135)
        badChars.append(136)
        badChars.append(137)
        badChars.append(138)
        badChars.append(139)
        badChars.append(140)
        badChars.append(141)
        badChars.append(142)
        badChars.append(143)
        badChars.append(144)
        badChars.append(145)
        badChars.append(146)
        badChars.append(147)
        badChars.append(148)
        badChars.append(149)
        badChars.append(150)
        badChars.append(151)
        badChars.append(152)
        badChars.append(153)
        badChars.append(154)
        badChars.append(155)
        badChars.append(156)
        badChars.append(157)
        badChars.append(158)
        badChars.append(159)
        badChars.append(160)
        badChars.append(161)
        badChars.append(162)
        badChars.append(163)
        badChars.append(164)
        badChars.append(165)
        badChars.append(166)
        badChars.append(167)
        badChars.append(168)
        badChars.append(169)
        badChars.append(170)
        badChars.append(171)
        badChars.append(172)
        badChars.append(173)
        badChars.append(174)
        badChars.append(175)
        badChars.append(176)
        badChars.append(177)
        badChars.append(178)
        badChars.append(179)
        badChars.append(180)
        badChars.append(181)
        badChars.append(182)
        badChars.append(183)
        badChars.append(184)
        badChars.append(185)
        badChars.append(186)
        badChars.append(187)
        badChars.append(188)
        badChars.append(189)
        badChars.append(190)
        badChars.append(191)
        badChars.append(192)
        badChars.append(193)
        badChars.append(194)
        badChars.append(195)
        badChars.append(196)
        badChars.append(197)
        badChars.append(198)
        badChars.append(199)
        badChars.append(200)
        badChars.append(201)
        badChars.append(202)
        badChars.append(203)
        badChars.append(204)
        badChars.append(205)
        badChars.append(206)
        badChars.append(207)
        badChars.append(208)
        badChars.append(209)
        badChars.append(210)
        badChars.append(211)
        badChars.append(212)
        badChars.append(213)
        badChars.append(214)
        badChars.append(215)
        badChars.append(216)
        badChars.append(217)
        badChars.append(218)
        badChars.append(219)
        badChars.append(220)
        badChars.append(221)
        badChars.append(222)
        badChars.append(223)
        badChars.append(224)
        badChars.append(225)
        badChars.append(226)
        badChars.append(227)
        badChars.append(228)
        badChars.append(229)
        badChars.append(230)
        badChars.append(231)
        badChars.append(232)
        badChars.append(233)
        badChars.append(234)
        badChars.append(235)
        badChars.append(236)
        badChars.append(237)
        badChars.append(238)
        badChars.append(239)
        badChars.append(240)
        badChars.append(241)
        badChars.append(242)
        badChars.append(243)
        badChars.append(244)
        badChars.append(245)
        badChars.append(246)
        badChars.append(247)
        badChars.append(248)
        badChars.append(249)
        badChars.append(250)
        badChars.append(251)
        badChars.append(252)
        badChars.append(253)
        badChars.append(254)
        badChars.append(255)
        badChars.append(256)
        badChars.append(257)
        badChars.append(258)
        badChars.append(259)
        badChars.append(260)
        badChars.append(261)
        badChars.append(262)
        badChars.append(263)
        badChars.append(264)
        badChars.append(265)
        badChars.append(266)
        badChars.append(267)
        badChars.append(268)

